name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-focal
      env: 
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo 'Start shopping store app'
          chmod +x ./shopping-store-linux-amd64 &
          echo 'Instal dependecies from lockfile'
          npm ci
          echo 'Run playwright tests'
          npm run test:ci
